disallowed-types = [
    { path = "std::collections::HashMap", reason = "use `hashbrown::HashMap` instead" },
    { path = "std::collections::HashSet", reason = "use `hashbrown::HashSet` instead" },
]
