name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  VERSION: ${{ github.event.inputs.version }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          pip install requests
          python x.py ci
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: dist/*
  Release: 
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          name: ${{ github.event.inputs.version == 'nightly' && 'Nightly' || github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version == 'nightly' && 'Nightly' || github.event.inputs.version }}
          draft: true
          prerelease: ${{ github.event.inputs.version == 'nightly' }}
          make_latest: true
          body: |
            ## Solo ${{ github.event.inputs.version == 'nightly' && 'Nightly' || github.event.inputs.version }}
          token: ${{ secrets.GHTOKEN }}